import type { Metadata } from "next";
import { Geist, Nunito_Sans, Bitcount_Grid_Single } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const bitcountGrid = Bitcount_Grid_Single({
  variable: "--font-bitcountgrid",
  subsets: ["latin"],
});

const nunitoSans = Nunito_Sans({
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${nunitoSans.variable}
           ${bitcountGrid.variable} antialiased`}
        >
          <Header />
          <div className="min-h-screen flex">
            <Sidebar />
            <div
              className="flex-1 bg-gray-100 p-4
               overflow-y-auto scrollbar-hide"
            >
              {children}
            </div>
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
